var TEXTS = {
    pl: {
        "pageTitle": "{name}, Możesz wszystko!",
        "header": "Cześć {name}!",
        "play": "Start",
        "yourName": "Twoje imię",
        "create": "Stwórz!",
        "waitForIt": "Jeszcze chwilkę...",
        "createYourOwn": "Stwórz własne.",
        "texts": [
            "<em>Jest</em> taka osoba<span>, która zna rozwiązania naszych problemów</span></span>",
            "<em>Jest</em> taka osoba<span>, która jest zawsze tam gdzie jest potrzebna</span></span>",
            "<em>Ż</em>adna siła <span>nie jest w stanie jej zatrzymać</span>",
            "<span>Tą osobą jesteś <em>Ty</em>!</span>",
            "<em>M</em>ożesz pokonać każdą przeszkodę",
            "<em>M</em>ożesz stać się silniejszy od każdego przeciwnika",
            "<em>M</em>ożesz rozwiązać każdy problem",
            "<em>M</em>ożesz przełamać każdą barierę",
            "<em>M</em>ożesz zwyciężyć każdą bitwę",
            "<em>M</em>ożesz znieść każdy ciężar",
            "<em>M</em>ożesz zdać każdy egzamin",
            "<em>M</em>ożesz być lepszy od każdego mistrza",
            "<em>M</em>ożesz przerosnąć dowolne oczekiwania",
            "<em>M</em>ożesz wygrać każdą grę",
            "<em>M</em>ożesz stworzyć arcydzieło",
            "<em>M</em>ożesz stać się mądrzejszy od kogokolwiek",
            "<em>M</em>ożesz osiągnąć niemożliwe",
            "<em>T</em>y wpływasz na wszystkich dookoła",
            "zmieniając świat na zawsze.",
            "<em>N</em>ic nie byłoby takie samo bez Ciebie...",
            "bo...",
            "<span><em>M</em>ożesz Wszystko!</span>"
        ]
    },
    en: {
        "pageTitle": "{name}, You Are Mighty!",
        "header": "Hi {name}!",
        "play": "Play",
        "yourName": "Your name",
        "create": "Create!",
        "waitForIt": "Wait for it...",
        "createYourOwn": "Create your own.",
        "texts": [
            "<em>O</em>ne individual <span>always has answers to our problems</span>",
            "<em>O</em>ne individual <span>is always there when called upon</span>",
            "<em>N</em>o mortal <span>can deter this individual</span>",
            "<span>This person is <em>you</em>!</span>",
            "<em>Y</em>ou can overcome any obstacle",
            "<em>Y</em>ou can overpower any enemy",
            "<em>Y</em>ou can solve any problem",
            "<em>Y</em>ou can break any barrier",
            "<em>Y</em>ou can conquer any battle",
            "<em>Y</em>ou can destroy any fortress",
            "<em>Y</em>ou can pass any test",
            "<em>Y</em>ou can surpass any master",
            "<em>Y</em>ou can exceed all expectations",
            "<em>Y</em>ou can win any game",
            "<em>Y</em>ou can create a masterpiece",
            "<em>Y</em>ou can outsmart anybody",
            "<em>Y</em>ou can do the impossible",
            "<em>Y</em>ou influence everyone around you",
            "changing the world forever.",
            "<em>N</em>othing would be the same without you...",
            "because...",
            "<span><em>Y</em>ou Are Mighty!</span>"
        ]
    }
}
